# Download historical equity data for NASDAQ stocks from yahoo finance

In [1]:
import warnings

warnings.filterwarnings("ignore")

In [3]:
from time import time
from tqdm import tqdm
from pathlib import Path
import pandas as pd
import yfinance as yf
import requests
from io import StringIO

In [4]:
idx = pd.IndexSlice

In [5]:
results_path = Path("results", "asset_pricing")
if not results_path.exists():
    results_path.mkdir(parents=True)

In [6]:
def chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i : i + n]

In [7]:
def format_time(t):
    """Return a formatted time string 'HH:MM:SS
    based on a numeric time() value"""
    m, s = divmod(t, 60)
    h, m = divmod(m, 60)
    return f"{h:0>2.0f}:{m:0>2.0f}:{s:0>2.0f}"

## Get NASDAQ symbols

In [9]:
def get_nasdaq_symbols():
    url = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt"
    response = requests.get(url)
    if response.status_code != 200:
        raise Exception(f"Failed to fetch data: {response.status_code}")

    # Remove the footer line "File Creation Time: ..."
    lines = response.text.strip().split("\n")
    cleaned_text = "\n".join(lines[:-1])

    df = pd.read_csv(StringIO(cleaned_text), sep="|")
    
    # Optional: filter out test issues or other flags
    df = df[df["Test Issue"] == "N"].dropna()
    
    return df

In [10]:
traded_symbols = get_nasdaq_symbols()

In [11]:
traded_symbols.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5000 entries, 0 to 5008
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Symbol            5000 non-null   object
 1   Security Name     5000 non-null   object
 2   Market Category   5000 non-null   object
 3   Test Issue        5000 non-null   object
 4   Financial Status  5000 non-null   object
 5   Round Lot Size    5000 non-null   int64
 6   ETF               5000 non-null   object
 7   NextShares        5000 non-null   object
dtypes: int64(1), object(7)
memory usage: 351.6+ KB

## Download metadata from yahoo finance

### NASDAQ symbols

In [12]:
all_symbols = list(traded_symbols[traded_symbols.ETF == 'N'].Symbol.unique())
n = len(all_symbols)
print(f"# Symbols: {n:,.0f}")

# Symbols: 4,064

In [13]:
DATA_STORE = '../data/assets.h5'

In [15]:
with pd.HDFStore(DATA_STORE) as store:
    prices = store['/stooq/us/nasdaq/stocks/prices']

In [24]:
with pd.HDFStore(DATA_STORE) as store:
    quandl = store['quandl/wiki/prices']

In [27]:
quandl_filt = quandl[quandl.index.get_level_values(1).isin(all_symbols)]

In [33]:
quandl_filt = quandl_filt[~quandl_filt.index.get_level_values(1).isin(curr_tickers)]

In [35]:
len(quandl_filt.index.get_level_values(1).unique())

48

In [37]:
quandl_final = quandl_filt.loc[idx['2008':'2019', :], :].filter(like='adj_').dropna().swaplevel().rename(columns=lambda x: x.replace('adj_', ''))

In [43]:
prices_filt = prices_filt.dropna()

In [44]:
prices_filt.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4431762 entries, ('AACG', Timestamp('2008-01-28 00:00:00')) to ('ZYXI', Timestamp('2019-12-31 00:00:00'))
Data columns (total 5 columns):
 #   Column  Dtype
---  ------  -----
 0   open    float64
 1   high    float64
 2   low     float64
 3   close   float64
 4   volume  float64
dtypes: float64(5)
memory usage: 186.2+ MB

In [42]:
quandl_final.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 99429 entries, ('ACFN', Timestamp('2008-01-02 00:00:00')) to ('TCBI', Timestamp('2018-03-27 00:00:00'))
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   open    99429 non-null  float64
 1   high    99429 non-null  float64
 2   low     99429 non-null  float64
 3   close   99429 non-null  float64
 4   volume  99429 non-null  float64
dtypes: float64(5)
memory usage: 4.9+ MB

In [47]:
data = pd.concat([prices_filt, quandl_final], axis = 0)

In [49]:
data = data.sort_index(level=['ticker', 'date'])

In [50]:
data

                     open    high     low   close      volume
ticker date
AACG   2008-01-28  0.7380  0.7380  0.7380  0.7380         0.0
       2008-01-29  0.7380  0.7760  0.6657  0.6797  19169939.0
       2008-01-30  0.6797  0.7108  0.6448  0.6603   2818723.0
       2008-01-31  0.6595  0.8001  0.6595  0.7418   2345961.0
       2008-02-01  0.7714  0.7721  0.7380  0.7387    361853.0
...                   ...     ...     ...     ...         ...
ZYXI   2019-12-24  7.0929  7.3630  6.9854  7.3360    148995.0
       2019-12-26  7.2999  7.4350  7.1199  7.2370    141086.0
       2019-12-27  7.2189  7.5520  7.1650  7.2460    263370.0
       2019-12-30  7.2460  7.3089  6.9760  7.1650    164479.0
       2019-12-31  7.0570  7.2640  6.9309  7.0839    130535.0

[4531191 rows x 5 columns]

In [18]:
prices.index = prices.index.set_levels(
    prices.index.levels[0].str.replace('.US', '', regex=False), level=0
)

In [19]:
prices

                     open    high     low   close      volume
ticker date
AACG   2008-01-28  0.7380  0.7380  0.7380  0.7380         0.0
       2008-01-29  0.7380  0.7760  0.6657  0.6797  19169939.0
       2008-01-30  0.6797  0.7108  0.6448  0.6603   2818723.0
       2008-01-31  0.6595  0.8001  0.6595  0.7418   2345961.0
       2008-02-01  0.7714  0.7721  0.7380  0.7387    361853.0
...                   ...     ...     ...     ...         ...
ZYXI   2019-12-24  7.0929  7.3630  6.9854  7.3360    148995.0
       2019-12-26  7.2999  7.4350  7.1199  7.2370    141086.0
       2019-12-27  7.2189  7.5520  7.1650  7.2460    263370.0
       2019-12-30  7.2460  7.3089  6.9760  7.1650    164479.0
       2019-12-31  7.0570  7.2640  6.9309  7.0839    130535.0

[4654102 rows x 5 columns]

In [20]:
prices_filt = prices[prices.index.get_level_values(0).isin(all_symbols)]

In [31]:
curr_tickers = list(prices_filt.index.get_level_values(0).unique())

In [59]:
yf_symbols = yf.Tickers(all_symbols)

In [60]:
meta_data = []
start = time()
for ticker, yf_object in tqdm(yf_symbols.tickers.items()):
    try:
        s = pd.Series(yf_object.get_info())
        meta_data.append(s.to_frame(ticker))
    except Exception as e:
        # track errors
        print(ticker, e)

print(f"Success: {len(meta_data):5,.0f} / {n:5,.0f}")

100%|██████████| 4064/4064 [17:28<00:00,  3.88it/s]

Success: 4,064 / 4,064

In [61]:
df = pd.concat(meta_data, axis=1).dropna(how="all").T
df = df.apply(pd.to_numeric, errors="ignore")
df.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
Index: 4064 entries, AACB to ZYXI
Columns: 205 entries, address1 to exchangeTransferDate
dtypes: bool(5), float64(140), int64(8), object(52)
memory usage: 6.3+ MB

In [62]:
df.to_hdf(results_path / "data.h5", "stocks/info")

## Download adjusted price data using yfinance

In [73]:
prices_adj = []
start = time()
for i, chunk in enumerate(chunks(all_symbols, 100), 1):
    prices_adj.append(yf.download(chunk, start='1990-01-01', end='2019-12-31', auto_adjust=True).stack(-1))

    per_ticker = (time() - start) / (i * 100)
    to_do = n - (i * 100)
    to_go = to_do * per_ticker
    print(
        f"Success: {len(prices_adj):5,.0f}/{i:5,.0f} | To go: {format_time(to_go)} ({to_do:5,.0f})"
    )

[*********************100%***********************]  100 of 100 completed

51 Failed downloads:
['AACIW', 'ADNWW', 'ABLVW', 'ABPWW', 'ADSEW', 'AEVAW', 'ADVWW', 'ACONW', 'ABLLW', 'ABVEW', 'AERTW', 'AENTW', 'AACBR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['ADV', 'ADXN', 'AACIU', 'ACTU', 'ABLLL', 'ACOG', 'AAPG', 'ABL', 'ACGLN', 'ACT', 'ABLV', 'ABVE', 'ACRV', 'AACB', 'ADSE', 'ABOS', 'ACXP', 'ADGM', 'AEVA', 'AENT', 'ABNB', 'ABCL', 'ACDC', 'AEBI', 'AEI', 'AERT', 'ABVX', 'ADAG', 'ADVB', 'AACBU', 'ABSI', 'ACON', 'ACLX', 'ADUR', 'ADTX', 'AARD', 'AACI', 'ABP']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     5%                       ]  5 of 100 completed

Success:     1/    1 | To go: 00:06:33 (3,964)

[*********************100%***********************]  100 of 100 completed

50 Failed downloads:
['AIFER', 'ALCYW', 'AIMDW', 'ALFUW', 'ALDFW', 'AISPW', 'AFJKR', 'AIRJW', 'AFRIW', 'ALVOW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['AIP', 'AFCG', 'AMIX', 'ALF', 'ALVO', 'AGH', 'AFJK', 'ALHC', 'AIRJ', 'ALDF', 'ALCY', 'ALGS', 'AIXI', 'ALZN', 'AGNCL', 'AIRS', 'AIFEU', 'AIFE', 'AGRI', 'AKAN', 'ALXO', 'AFRI', 'ALKT', 'AGFY', 'ALCYU', 'AFJKU', 'ALAB', 'AFRM', 'ALLR', 'AISP', 'ALFUU', 'ALDFU', 'ALTI', 'AIRO', 'ALMS', 'AIMD', 'ALGM', 'AGNCP', 'ALMU', 'AIRE']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      2%                       ]  2 of 100 completed

Success:     2/    2 | To go: 00:05:28 (3,864)

[*********************100%***********************]  100 of 100 completed

46 Failed downloads:
['ASBPW', 'ANGHW', 'ANNAW', 'ARBEW', 'AREBW', 'ARKOW', 'AMODW', 'ANSCW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['AMST', 'ARM', 'AREB', 'AMPGW', 'AMPG', 'ARBK', 'ANTX', 'ARHS', 'APADU', 'ARBB', 'ANPA', 'ARBE', 'ANSCU', 'ASBP', 'ANNA', 'APLD', 'ANTA', 'AMOD', 'AMLX', 'ARAI', 'ANGH', 'AMPL', 'API', 'ARQT', 'ANL', 'ARBKL', 'APGE', 'ARTV', 'APLM', 'AOUT', 'ANEB', 'ANNX', 'ARQQ', 'ARRY', 'ARQQW', 'APP', 'APLMW', 'ANSC']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:     3/    3 | To go: 00:04:58 (3,764)

[*********************100%***********************]  100 of 100 completed

51 Failed downloads:
['ATNFW', 'AUROW', 'ATMVR', 'ASPCR', 'ASPSW', 'ATIIW', 'ATMCW', 'AUUDW', 'AXINR', 'ASPSZ', 'ASTLW', 'ATMCR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['ATLN', 'ATMVU', 'ASPI', 'ATLCP', 'AUR', 'AVO', 'AZI', 'ATHA', 'AUGO', 'ASTL', 'AXINU', 'ATLCL', 'AURA', 'ATMV', 'AUUD', 'ATAT', 'AVBP', 'AVDX', 'ATGL', 'AXIN', 'ATMCU', 'ATIIU', 'AUID', 'ATPC', 'ASO', 'ASST', 'AVR', 'AVIR', 'ATMC', 'ATLCZ', 'ATII', 'ASTI', 'ASNS', 'ASPC', 'ATAI', 'ATHR', 'AZ', 'AVAH', 'ASPCU']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[****                   8%                       ]  8 of 100 completed

Success:     4/    4 | To go: 00:04:35 (3,664)

[*********************100%***********************]  100 of 100 completed

59 Failed downloads:
['BETRW', 'BCTXW', 'BEAGR', 'BCTXZ', 'BEATW', 'BENFW', 'BAYAR', 'BDMDW', 'BFRIW', 'BCGWW', 'BAERW', 'BIAFW', 'BGLWW', 'BFRGW', 'BACQR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['BBLG', 'BACQU', 'BEAGU', 'BEEP', 'BCAB', 'BACCU', 'BHFAO', 'BGL', 'BKHA', 'BIVI', 'BIOA', 'BDTX', 'BBLGW', 'BANL', 'BACQ', 'BCARU', 'BETR', 'BIYA', 'BDMD', 'BINI', 'BJDX', 'BEAG', 'BAER', 'BHST', 'BFRG', 'BFRI', 'BHFAN', 'BGM', 'BENF', 'BEAT', 'BGLC', 'BAYAU', 'BHFAM', 'BCG', 'BEAM', 'BAYA', 'BASE', 'BIAF', 'BDSX', 'BAOS', 'BIRD', 'BCAX', 'BAFN', 'BBNX']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:     5/    5 | To go: 00:04:27 (3,564)

[*********************100%***********************]  100 of 100 completed

53 Failed downloads:
['BMBL', 'BOF', 'BMEA', 'BSAAU', 'BSBK', 'BNAI', 'BRLT', 'BOLT', 'BSY', 'BTMD', 'BPYPM', 'BON', 'BRRWW', 'BTSG', 'BKHAU', 'BLMZ', 'BTM', 'BRR', 'BLIV', 'BLFY', 'BOWNU', 'BTBD', 'BNRG', 'BMHL', 'BMGL', 'BLZE', 'BLUW', 'BTOC', 'BREA', 'BOLD', 'BRNS', 'BLUWU', 'BPYPN', 'BSLK', 'BOWN', 'BNZI', 'BLTE', 'BMR', 'BRLS', 'BRZE', 'BNR', 'BTDR', 'BRRWU']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['BTBDW', 'BSLKW', 'BOWNR', 'BNAIW', 'BTMWW', 'BLUWW', 'BNZIW', 'BLDEW', 'BKHAR', 'BRLSW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[                       0%                       ]

Success:     6/    6 | To go: 00:04:27 (3,464)

[*********************100%***********************]  99 of 100 completed

48 Failed downloads:
['CDRO', 'CAPN', 'CADL', 'CALC', 'BZAI', 'CAPNU', 'CCIX', 'CAI', 'CCGWW', 'BULL', 'CCTG', 'CCSI', 'CCLDO', 'BTSGU', 'CCG', 'BULLW', 'BUSEP', 'BWMN', 'CCIRU', 'BWBBP', 'BZ', 'CCIIU', 'CCCX', 'CCIXU', 'CCIR', 'CDIO', 'CCAP', 'BZFD', 'BVS', 'CAEP', 'CAPT', 'CCCXU', 'CBLL', 'CCNEP', 'CCCS', 'CARL', 'CAMP', 'CCCC', 'CART', 'CASK']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['CAPTW', 'CCIRW', 'BZAIW', 'CDIOW', 'BZFDW', 'CDROW', 'CCIXW', 'CCCXW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[*                      3%                       ]  3 of 100 completed

Success:     7/    7 | To go: 00:04:17 (3,364)

[*********************100%***********************]  100 of 100 completed

47 Failed downloads:
['CINGW', 'CHACR', 'CHPGR', 'CGCTW', 'CELUW', 'CEROW', 'CDTTW', 'CIFRW', 'CHARR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['CGNT', 'CGABL', 'CFLT', 'CHARU', 'CDT', 'CHAR', 'CDTG', 'CEG', 'CEPT', 'CISS', 'CLBT', 'CHSN', 'CGBDL', 'CDZIP', 'CERT', 'CERO', 'CHYM', 'CHAC', 'CEP', 'CGCT', 'CGTX', 'CHA', 'CEPO', 'CING', 'CGTL', 'CGEM', 'CGCTU', 'CETY', 'CJMB', 'CISO', 'CFSB', 'CHPGU', 'CJET', 'CIGL', 'CGON', 'CIFR', 'CHACU', 'CHPG']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      3%                       ]  3 of 100 completed

Success:     8/    8 | To go: 00:04:12 (3,264)

[*********************100%***********************]  100 of 100 completed

43 Failed downloads:
['CRAQR', 'COOTW', 'CNCKW', 'CLSKW', 'COCHW', 'COEPW', 'COLAR', 'CORZZ', 'CORZW', 'CMPOW', 'CLNNW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['CRBU', 'CMRC', 'CMPX', 'CRCT', 'CNEY', 'CNOBP', 'COOT', 'CPBI', 'CLYM', 'COYA', 'CLOV', 'COLAU', 'CNXC', 'CNTX', 'CMPS', 'CMPO', 'CLIK', 'CRAQ', 'COEP', 'CNFRZ', 'CNCK', 'CPOP', 'CORZ', 'CNTB', 'CLST', 'CMND', 'CNTA', 'COIN', 'COLA', 'CRAQU', 'COCO', 'COCH']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:     9/    9 | To go: 00:03:58 (3,164)

[*********************100%***********************]  100 of 100 completed

37 Failed downloads:
['CVKD', 'CRWV', 'CVRX', 'CRSR', 'CWD', 'CTNT', 'CRGX', 'CRDO', 'CUB', 'CTOR', 'CRML', 'CUBWU', 'CYCU', 'CURI', 'CURR', 'CRGO', 'CSWCZ', 'CV', 'CYN', 'CVAC', 'DAAQ', 'CXAI', 'CTKB', 'CRE', 'CSAI', 'CREV', 'DAAQU', 'CUPR', 'CTNM']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['CURIW', 'CYCUW', 'CREVW', 'CRMLW', 'CXAIW', 'CRGOW', 'CUBWW', 'CRESW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[**                     4%                       ]  4 of 100 completed

Success:    10/   10 | To go: 00:03:49 (3,064)

[*********************100%***********************]  99 of 100 completed

56 Failed downloads:
['DHAIW', 'DSYWW', 'DRTSW', 'DRDBW', 'DHCNL', 'DRMAW', 'DMAAR', 'DAVEW', 'DFLIW', 'DAAQW', 'DFSCW', 'DAICW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['DRVN', 'DFSC', 'DSP', 'DTCK', 'DCOMP', 'DASH', 'DFDV', 'DATSW', 'DJT', 'DNUT', 'DATS', 'DMAAU', 'DLO', 'DH', 'DCOMG', 'DAWN', 'DALN', 'DRTS', 'DEFT', 'DRDB', 'DEVS', 'DGNX', 'DRUG', 'DCGO', 'DLXY', 'DTI', 'DHAI', 'DAVE', 'DMAA', 'DCBO', 'DJTWW', 'DTSQ', 'DFLI', 'DERM', 'DRCT', 'DSGN', 'DSY', 'DRDBU', 'DIBS', 'DGXX', 'DPRO', 'DAIC', 'DRMA', 'DDI']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      3%                       ]  3 of 100 completed

Success:    11/   11 | To go: 00:03:42 (2,964)

[*********************100%***********************]  100 of 100 completed

53 Failed downloads:
['EMCGR', 'EGHAR', 'DTSQR', 'EMCGW', 'ECXWW', 'ECDAW', 'ENGNW', 'DYNXW', 'DTSTW', 'DYCQR', 'EDBLW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['ENVXW', 'ELVN', 'DYCQ', 'EFSCP', 'EMPG', 'ENGS', 'EMCGU', 'ENGN', 'EHLD', 'DWTX', 'ENVX', 'EGHA', 'ELWS', 'EM', 'EMCG', 'DYNXU', 'EBC', 'EJH', 'EDBL', 'ELAB', 'DYCQU', 'EDTK', 'DYNX', 'ELTX', 'ELPW', 'ELBM', 'ELUT', 'DUOL', 'EGHAU', 'ECBK', 'ECDA', 'EHGO', 'DXST', 'ENLT', 'EEIQ', 'ECX', 'EMBC', 'EDHL', 'DYN', 'EBON', 'DTSQU', 'EMPD']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      3%                       ]  3 of 100 completed

Success:    12/   12 | To go: 00:03:34 (2,864)

[*********************100%***********************]  100 of 100 completed

49 Failed downloads:
['ESLAW', 'EURKR', 'FBYDW', 'ESGLW', 'FAASW', 'FACTW', 'EUDAW', 'EVLVW', 'ESHAR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['FACTU', 'EWTX', 'EOSEW', 'FATN', 'ESHA', 'FBGL', 'EXEEL', 'EVGO', 'ERAS', 'EVAX', 'EXEEW', 'FACT', 'FAAS', 'FBYD', 'EURK', 'EXOZ', 'FBLG', 'EURKU', 'EWCZ', 'EOSE', 'FA', 'FBLA', 'EZGO', 'EXEEZ', 'ETHA', 'FATBB', 'EPWK', 'FATBP', 'EVCM', 'EPRX', 'EUDA', 'EPSM', 'EVGOW', 'ESLA', 'ESGL', 'EPOW', 'EVLV', 'EXE', 'ETOR', 'EXFY']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[                       0%                       ]

Success:    13/   13 | To go: 00:03:27 (2,764)

[*********************100%***********************]  100 of 100 completed

41 Failed downloads:
['FERAR', 'FGMCR', 'FMSTW', 'FFAIW', 'FGIWW', 'FORLW', 'FLDDW', 'FOXXW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['FEMY', 'FDMT', 'FERA', 'FEBO', 'FFAI', 'FEAM', 'FGBIP', 'FIP', 'FORA', 'FGMCU', 'FERAU', 'FLUX', 'FLNC', 'FGMC', 'FORL', 'FLX', 'FINW', 'FOXX', 'FMFC', 'FLYE', 'FLGC', 'FLYW', 'FHTX', 'FCNCO', 'FGI', 'FORLU', 'FLD', 'FMST', 'FIGXU', 'FDSB', 'FOSLL', 'FGL', 'FCNCP']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      2%                       ]  2 of 100 completed

Success:    14/   14 | To go: 00:03:18 (2,664)

[*********************100%***********************]  100 of 100 completed

51 Failed downloads:
['GCMGW', 'FUFUW', 'GCLWW', 'GECCZ', 'GDEVW', 'FSHPR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['FRSH', 'FTCI', 'GAINZ', 'GAUZ', 'GAINL', 'FROG', 'FSHPU', 'FSBC', 'GCT', 'GEHC', 'GDHG', 'GDRX', 'GECCO', 'GDTC', 'GDEV', 'FSHP', 'FVNNR', 'FWRG', 'GAINN', 'GBFH', 'GANX', 'FTEL', 'GELS', 'GAINI', 'FTAIN', 'GAMB', 'FSUN', 'GENVR', 'GCL', 'FTRE', 'GENK', 'GFAI', 'GBIO', 'FULTP', 'GECCH', 'FUFU', 'FVNNU', 'GEGGL', 'GECCI', 'FYBR', 'FTRK', 'FTHM', 'FVN', 'FTAIM', 'FRMEP']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      3%                       ]  3 of 100 completed

Success:    15/   15 | To go: 00:03:11 (2,564)

[*********************100%***********************]  100 of 100 completed

51 Failed downloads:
['GRRRW', 'GFAIW', 'GOVXW', 'GSHRW', 'GIPRW', 'GGROW', 'GIGGW', 'GIBOW', 'GPATW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['GLE', 'GLADZ', 'GPCR', 'GLXY', 'GSHR', 'GHRS', 'GOVX', 'GSRT', 'GIFT', 'GIBO', 'GMHS', 'GITS', 'GGR', 'GPAT', 'GNTA', 'GSRTR', 'GRAB', 'GRAN', 'GPATU', 'GLBE', 'GLUE', 'GIPR', 'GSIW', 'GSHRU', 'GIG', 'GLSI', 'GNLX', 'GP', 'GRI', 'GLXG', 'GOCO', 'GOODO', 'GMM', 'GRRR', 'GRABW', 'GLTO', 'GRAL', 'GFS', 'GLIBA', 'GLIBK', 'GREEL', 'GIGGU']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      3%                       ]  3 of 100 completed

Success:    16/   16 | To go: 00:03:02 (2,464)

[*********************100%***********************]  100 of 100 completed

52 Failed downloads:
['GTERR', 'HOVRW', 'GTERW', 'HOLOW', 'GTENW', 'HPAIW', 'HONDW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['HKIT', 'GV', 'HNST', 'GVH', 'HCAI', 'HPAI', 'HCHL', 'GUTS', 'GTLB', 'HOVR', 'HNNAZ', 'HLP', 'HCTI', 'HNVR', 'GXAI', 'HOND', 'HLMN', 'HCMAU', 'HDL', 'HOUR', 'HKPD', 'GSUN', 'GTM', 'HITI', 'HBNB', 'HEPS', 'HMR', 'HBANL', 'HBANP', 'HIT', 'GTI', 'GTENU', 'HONDU', 'GTERA', 'GSRTU', 'HOWL', 'HLXB', 'GTERU', 'HLVX', 'HBANM', 'HAO', 'HCWB', 'HOOD', 'GTEN', 'HOLO']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     5%                       ]  5 of 100 completed

Success:    17/   17 | To go: 00:02:54 (2,364)

[*********************100%***********************]  100 of 100 completed

50 Failed downloads:
['HSPOR', 'HUMAW', 'HTZWW', 'IBACR', 'HSCSW', 'ICUCW', 'HVIIR', 'HUBCZ', 'HUBCW', 'HSPOW', 'HSPTR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['HVII', 'HSPO', 'HYFM', 'HTLM', 'HROWL', 'HSCS', 'HWCPZ', 'ICU', 'HTCR', 'IBAC', 'HYMCL', 'IBIT', 'HSPTU', 'IDAI', 'HUMA', 'HTZ', 'HTOOW', 'HUBC', 'IBG', 'HUDI', 'HSPOU', 'HSPT', 'HXHX', 'ICCM', 'HTCO', 'IBEX', 'HVIIU', 'ICG', 'HRMY', 'IFBD', 'HTOO', 'IAS', 'HUHU', 'HUIZ', 'ICON', 'HSAI', 'HWH', 'HROWM', 'HYPR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    18/   18 | To go: 00:02:46 (2,264)

[*********************100%***********************]  100 of 100 completed

45 Failed downloads:
['IINN', 'IOTR', 'IPCX', 'INTR', 'ILAG', 'IMCC', 'IMMX', 'IMG', 'IMNM', 'IONR', 'INBS', 'INBX', 'INNV', 'IMRX', 'IPSC', 'IMAB', 'IKT', 'IINNW', 'IMA', 'INKT', 'INAB', 'INEO', 'INTS', 'IOBT', 'IPODU', 'INACU', 'IPOD', 'IPX', 'IMPPP', 'INLF', 'IPCXU', 'INVZ', 'IPW', 'IMCR', 'INV', 'INTA', 'INHD', 'IMPP', 'INAC', 'INTJ']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['INVZW', 'INACR', 'IPODW', 'IPCXR', 'ILLRW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[*                      3%                       ]  3 of 100 completed

Success:    19/   19 | To go: 00:02:38 (2,164)

[*********************100%***********************]  100 of 100 completed

52 Failed downloads:
['IROHW', 'KFIIR', 'JSPRW', 'ISRLW', 'IVDAW', 'KCHVR', 'IROHR', 'JFBRW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['JCSE', 'KARO', 'IVVD', 'JTAI', 'ITOS', 'KC', 'JFB', 'KBSX', 'KAVL', 'JUNS', 'IVA', 'KCHV', 'JWEL', 'IROH', 'IVP', 'JFBR', 'ISRL', 'JBDI', 'IRON', 'IVF', 'KFIIU', 'JLHL', 'JZ', 'JSPR', 'IROHU', 'JCAP', 'ISPO', 'JBIO', 'IZM', 'JANX', 'JEM', 'ISPC', 'IXHL', 'JZXN', 'JAMF', 'JDZG', 'KFII', 'KCHVU', 'JL', 'ISPOW', 'ISRLU', 'JYD', 'ISPR', 'IREN']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    20/   20 | To go: 00:02:31 (2,064)

[*********************100%***********************]  100 of 100 completed

46 Failed downloads:
['KITTW', 'KVACW', 'LCCCR', 'KTTAW', 'LEXXW', 'KWMWW', 'LCFYW', 'KIDZW', 'KPLTW', 'KLTOW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['LBGJ', 'KITT', 'KLTO', 'LANDP', 'KSPI', 'LENZ', 'LFST', 'KMTS', 'LCFY', 'LCCCU', 'LANDM', 'KWM', 'LBRDP', 'LEGN', 'KROS', 'LCID', 'KYMR', 'KLRS', 'LASE', 'LEXX', 'LFMDP', 'KYTX', 'KLTR', 'KTTA', 'KMRK', 'LAWR', 'LANDO', 'KSCP', 'KVAC', 'KRT', 'KVACU', 'KPLT', 'LCCC', 'KIDZ', 'LESL', 'LAES']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[                       0%                       ]

Success:    21/   21 | To go: 00:02:23 (1,964)

[*********************100%***********************]  100 of 100 completed

49 Failed downloads:
['LNZAW', 'LOTWW', 'LTRYW', 'LIMNW', 'LPAAW', 'LOKVW', 'LSBPW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['LRE', 'LPAAU', 'LIDRW', 'LGCB', 'LLYVA', 'LRHC', 'LUCY', 'LINE', 'LIF', 'LIDR', 'LOBO', 'LUNR', 'LPAA', 'LNZA', 'LIMN', 'LI', 'LHSW', 'LIEN', 'LNKS', 'LOKVU', 'LNSR', 'LSB', 'LUCYW', 'LUCD', 'LPBB', 'LSE', 'LOKV', 'LPBBU', 'LGCL', 'LIXTW', 'LPBBW', 'LOT', 'LNKB', 'LSH', 'LGVN', 'LVLU', 'LICN', 'LTRN', 'LLYVK', 'LITM', 'LHAI', 'LUNG']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    22/   22 | To go: 00:02:15 (1,864)

[*********************100%***********************]  100 of 100 completed

52 Failed downloads:
['MDAIW', 'MACIW', 'LVROW', 'MBAVW', 'MAYAR', 'MAPSW', 'METCI']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['MBNKO', 'MBLY', 'MBAVU', 'LZMH', 'MASS', 'MDAI', 'MBINM', 'MACIU', 'MEGL', 'MASK', 'MBX', 'MAZE', 'LVRO', 'LYRA', 'MB', 'MAMK', 'MBBC', 'MACI', 'LXEH', 'MENS', 'MAMO', 'MAMA', 'MBAV', 'MAYAU', 'MFI', 'LZ', 'MDBH', 'MCW', 'MDCX', 'MCTR', 'MBINL', 'LXEO', 'LVTX', 'METCL', 'MDCXW', 'MBINN', 'MDXH', 'LWACU', 'MAXN', 'LYEL', 'MCHPP', 'METCZ', 'MDIA', 'METCB', 'MAYA']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[                       0%                       ]

Success:    23/   23 | To go: 00:02:08 (1,764)

[*********************100%***********************]  100 of 100 completed

47 Failed downloads:
['MSAIW', 'MNTSW', 'MRNOW', 'MOBXW', 'MKDWW', 'MLACR', 'MLECW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['MRNO', 'MQ', 'MLAC', 'MKTW', 'MKDW', 'MKZR', 'MRX', 'MNDY', 'MRVI', 'MLTX', 'MNY', 'MLACU', 'MJID', 'MGRX', 'MSAI', 'MHUA', 'MLEC', 'MIRA', 'MNDR', 'MNYWW', 'MOBBW', 'MGX', 'MIMI', 'MSGM', 'MNTK', 'MOLN', 'MGIH', 'MSBIP', 'MLGO', 'MOB', 'MNSBP', 'MOVE', 'MGRM', 'MODD', 'MGRT', 'MNTS', 'MOBX', 'MFICL', 'MRM', 'MLYS']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    24/   24 | To go: 00:01:60 (1,664)

[*********************100%***********************]  100 of 100 completed

50 Failed downloads:
['NETDW', 'MVSTW', 'NAKAW', 'MTEKW', 'NEHCW', 'NCPLW', 'NEOVW', 'MSPRZ']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['MYNZ', 'NAMSW', 'NBTX', 'NAMI', 'MURA', 'MSS', 'NEWTZ', 'MXCT', 'NAMM', 'NB', 'MTEK', 'NEUP', 'MTEN', 'NETD', 'MSPR', 'NCEW', 'MSGY', 'NETDU', 'MYPS', 'NCI', 'NAKA', 'MTSR', 'NCRA', 'NESR', 'NAMMW', 'NCIQ', 'NBBK', 'NEOV', 'NEWTI', 'NBIS', 'NAMS', 'NEWTG', 'NCT', 'NEWTH', 'NCNO', 'NAUT', 'MSW', 'NEHC', 'MWYN', 'MYPSW', 'MSPRW', 'NEXN']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     5%                       ]  5 of 100 completed

Success:    25/   25 | To go: 00:01:53 (1,564)

[*********************100%***********************]  100 of 100 completed

53 Failed downloads:
['NRXPW', 'NNAVW', 'NVVEW', 'NIOBW', 'NTWOW', 'NIXXW', 'NRSNW', 'NOEMR', 'NHICW', 'NPACW', 'NIVFW', 'NVNIW', 'NOEMW', 'NVAWW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['NTRBW', 'NUTX', 'NVTS', 'NPACU', 'NTRB', 'NNE', 'NUKKW', 'NMFCZ', 'NRIX', 'NTWO', 'NIPG', 'NTWOU', 'NTHI', 'NSTS', 'NLSP', 'NRDS', 'NVNI', 'NRSN', 'NVA', 'NPAC', 'NPCE', 'NNNN', 'NUVL', 'NKTX', 'NVVE', 'NOEMU', 'NMPAU', 'NTCL', 'NUKK', 'NIVF', 'NHPBP', 'NLSPW', 'NN', 'NHIC', 'NNOX', 'NMRA', 'NVCT', 'NOEM', 'NHICU']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      3%                       ]  3 of 100 completed

Success:    26/   26 | To go: 00:01:45 (1,464)

[*********************100%***********************]  100 of 100 completed

58 Failed downloads:
['NWTNW', 'OACCW', 'OAKUW', 'OCSAW', 'NXPLW', 'ODVWZ', 'OABIW', 'NXLIW', 'NXGLW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['NYMTG', 'NYXH', 'OABI', 'OAKUR', 'ODYS', 'NXL', 'OMH', 'OBIO', 'OLMA', 'OFAL', 'NYAX', 'NWGL', 'NXTT', 'OMSE', 'NXXT', 'ONEG', 'NVX', 'NXT', 'OCCIO', 'OFSSO', 'OCCIM', 'OCG', 'OCS', 'NWTN', 'OLPX', 'OACC', 'ONBPP', 'OAKUU', 'NYMTI', 'NYMTL', 'NXGL', 'ONCHU', 'ONBPO', 'OCTO', 'OM', 'NYMTH', 'OBAWU', 'OAKU', 'OACCU', 'OMDA', 'OFSSH', 'OCCIN', 'OKUR', 'ODD', 'ONCO', 'NWTG', 'OKYO', 'NYMTZ', 'ONDS']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    27/   27 | To go: 00:01:38 (1,364)

[*********************100%***********************]  100 of 100 completed

49 Failed downloads:
['PBMWW', 'OUSTZ', 'OXBRW', 'OSRHW', 'ORGNW', 'OUSTW', 'OPTXW', 'ONFOW', 'ONMDW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['OXLCL', 'OYSER', 'OXLCO', 'ORKT', 'ONFO', 'OPINL', 'OYSEU', 'PAX', 'OS', 'ORIS', 'PAYO', 'ORIC', 'OPAL', 'ONMD', 'OUST', 'OXLCI', 'OYSE', 'OPTX', 'OXLCN', 'ONEW', 'OSRH', 'OTLY', 'PACHU', 'OXSQG', 'OPT', 'OST', 'OXLCP', 'PAL', 'OPEN', 'OP', 'OZKAP', 'PCAP', 'OXLCG', 'OXLCZ', 'ORIQU', 'ORGN', 'PBM', 'PASG', 'PBBK', 'PC']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     5%                       ]  5 of 100 completed

Success:    28/   28 | To go: 00:01:30 (1,264)

[*********************100%***********************]  100 of 100 completed

43 Failed downloads:
['PIIIW', 'PCAPW', 'PCTTW', 'PMTRW', 'PLMKW', 'PELIR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['PEPG', 'PMTR', 'PCLA', 'PNFPP', 'PECO', 'PLUT', 'PLTK', 'PLRZ', 'PFSA', 'PCAPU', 'PMEC', 'PELIU', 'PN', 'PHH', 'PFAI', 'PLMKU', 'PELI', 'PCTTU', 'PHOE', 'PGY', 'PHVS', 'PGYWW', 'PLTR', 'PMVP', 'PDYNW', 'PHAR', 'PCVX', 'PCT', 'PMAX', 'PDYN', 'PMTRU', 'PFXNZ', 'PIII', 'PLBY', 'PCSC', 'PLRX', 'PLMK']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[                       0%                       ]

Success:    29/   29 | To go: 00:01:22 (1,164)

[*********************100%***********************]  100 of 100 completed

39 Failed downloads:
['PRCH', 'PRLD', 'PYXS', 'QMMM', 'PRFX', 'PONY', 'PWM', 'PUBM', 'POLE', 'PRME', 'PRZO', 'PTHL', 'PRVA', 'PTIX', 'PODC', 'PTLE', 'PRAX', 'PSIG', 'PSNYW', 'QH', 'PSNY', 'PTLO', 'PWP', 'PRCT', 'PRE', 'QETAU', 'POLEU', 'POWWP', 'PRTC', 'PTNM', 'PPTA', 'PROK', 'QETA', 'PYPD']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['PRENW', 'PTIXW', 'POLEW', 'QETAR', 'PXSAW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[**                     4%                       ]  4 of 100 completed

Success:    30/   30 | To go: 00:01:17 (1,064)

[*********************100%***********************]  100 of 100 completed

53 Failed downloads:
['RFAIR', 'RAINW', 'RDAGW', 'RDZNW', 'RAAQW', 'RANGR', 'RGTIW', 'QSEAR', 'RDACR', 'REVBW', 'RCKTW', 'QSIAW', 'RELIW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['RDACU', 'RHLD', 'RAPP', 'QSEAU', 'QSG', 'REE', 'RECT', 'RENT', 'RAAQU', 'RADX', 'RCT', 'REFI', 'RAY', 'RBNE', 'RDZN', 'RANGU', 'RAIN', 'REGCP', 'RFAI', 'RDAGU', 'RGTI', 'RIBB', 'REAX', 'RAAQ', 'QSI', 'RANG', 'QVCGP', 'RELI', 'RGC', 'RFAIU', 'RELY', 'REVB', 'RDAC', 'RANI', 'QSEA', 'RDAG', 'REBN', 'REGCO', 'REYN', 'RAYA']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    31/   31 | To go: 00:01:09 (  964)

[*********************100%***********************]  100 of 100 completed

56 Failed downloads:
['RVMDW', 'SABSW', 'RIBBR', 'RUMBW', 'RZLVW', 'RMCOW', 'RVPHW', 'RMSGW', 'RVSNW', 'SAIHW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['RNAZ', 'RXST', 'RSVRW', 'RMSG', 'RKLB', 'RILYL', 'RNA', 'RILYT', 'RPRX', 'RTAC', 'RIBBU', 'RNW', 'RR', 'RTACU', 'ROIV', 'RILYK', 'RWAYZ', 'RILYZ', 'RLAY', 'SAFX', 'SAIL', 'ROMA', 'RMCO', 'RWAYL', 'ROOT', 'RVMD', 'SAIH', 'RNWWW', 'RTACW', 'RXRX', 'RPID', 'RIVN', 'RZLV', 'RPTX', 'RUM', 'SAGT', 'RSVR', 'RILYG', 'RITR', 'RLYB', 'RNXT', 'RVSN', 'RXT', 'RYET', 'SABS', 'RWAY']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    32/   32 | To go: 00:01:01 (  864)

[*********************100%***********************]  100 of 100 completed

47 Failed downloads:
['SDAWW', 'SATLW', 'SHMDW', 'SBCWW', 'SCAGW', 'SDHIR', 'SCLXW', 'SDSTW', 'SHOTW', 'SBFMW', 'SHFSW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['SELX', 'SBC', 'SHC', 'SDGR', 'SANA', 'SIDU', 'SCLX', 'SCAG', 'SEER', 'SEZL', 'SFWL', 'SDOT', 'SGMT', 'SDA', 'SDM', 'SHFS', 'SGHT', 'SEPN', 'SERV', 'SATL', 'SEATW', 'SGD', 'SHOT', 'SERA', 'SHIM', 'SBFM', 'SFD', 'SHMD', 'SEAT', 'SEGG', 'SFHG', 'SHPH', 'SDST', 'SHLS', 'SDHI', 'SDHIU']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[*                      2%                       ]  2 of 100 completed

Success:    33/   33 | To go: 00:00:53 (  764)

[*********************100%***********************]  100 of 100 completed

43 Failed downloads:
['SIMAW', 'SONDW', 'SMXWW', 'SLDPW', 'SLXNW', 'SOUNW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['SOPH', 'SNDK', 'SNCY', 'SNSE', 'SLDP', 'SIGIP', 'SMTK', 'SION', 'SNYR', 'SKYT', 'SKK', 'SOFI', 'SOCAU', 'SORA', 'SOPA', 'SKYQ', 'SKYX', 'SLXN', 'SIMAU', 'SIMA', 'SNRE', 'SNTG', 'SILO', 'SNWV', 'SKIN', 'SNTI', 'SMXT', 'SLN', 'SOGP', 'SLDE', 'SLNHP', 'SNAL', 'SKWD', 'SOND', 'SMX', 'SKBL', 'SOUN']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[                       0%                       ]

Success:    34/   34 | To go: 00:00:46 (  664)

[*********************100%***********************]  100 of 100 completed

53 Failed downloads:
['SWIM', 'SPEGU', 'SSII', 'SUUN', 'SPHL', 'STRF', 'SVRE', 'STI', 'STAK', 'SQFT', 'STEC', 'SUPX', 'STHO', 'SVIIU', 'SPWR', 'STKH', 'STRD', 'SRBK', 'SVCO', 'SPRC', 'SPRY', 'STRZ', 'STSS', 'SPPL', 'STRK', 'SRZN', 'SQFTP', 'SPKL', 'SSSSL', 'SPKLU', 'SUNS', 'STTK', 'STAI', 'STEP', 'STRC', 'STFS', 'SPAI', 'SUGP', 'SVII', 'SWAG', 'SRAD', 'SVCCU', 'SVCC']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['SPWRW', 'SVIIR', 'SVCCW', 'SQFTW', 'SWAGW', 'SRZNW', 'SPKLW', 'SVIIW', 'SVREW', 'STSSW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[*                      2%                       ]  2 of 100 completed

Success:    35/   35 | To go: 00:00:38 (  564)

[*********************100%***********************]  99 of 100 completed

51 Failed downloads:
['TBH', 'TCBX', 'TACHU', 'TACH', 'TACOU', 'SYTA', 'TASK', 'SWIN', 'SYM', 'SZZL', 'TDUP', 'TIL', 'TALK', 'TBLD', 'THCH', 'TEAD', 'TCBS', 'TEM', 'THAR', 'SZZLU', 'TACO', 'SWKHL', 'SXTP', 'TBLA', 'TGL', 'TFINP', 'TCBIO', 'SWVL', 'TAOX', 'TAVIU', 'TDTH', 'TERN', 'TDAC', 'TDACU', 'TARS', 'TAVI', 'TDIC', 'TCRX', 'TBMCR', 'TBMC', 'TELO']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['TDACW', 'SXTPW', 'SYTAW', 'TBLAW', 'SWVLW', 'TACOW', 'TALKW', 'TACHW', 'TAVIR', 'SZZLR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[*                      2%                       ]  2 of 100 completed

Success:    36/   36 | To go: 00:00:31 (  464)

[*********************100%***********************]  100 of 100 completed

48 Failed downloads:
['TVACW', 'TOIIW', 'TVGNW', 'TVAIR', 'TNONW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['TLSIW', 'TOP', 'TVAIU', 'TOI', 'TVA', 'TMCWW', 'TNMG', 'TVACU', 'TNON', 'TRINZ', 'TRINI', 'TRSG', 'TLX', 'TRON', 'TKLF', 'TNGX', 'TLIH', 'TIVC', 'TVGN', 'TLN', 'TOYO', 'TURB', 'TRNR', 'TSBX', 'TLS', 'TPGXL', 'TMCI', 'TNYA', 'TPG', 'TRUG', 'TVAI', 'TRML', 'TTAN', 'TRIN', 'TIRX', 'TSHA', 'TRDA', 'TORO', 'TKNO', 'TWG', 'TLSI', 'TMC', 'TWFG']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[***                    6%                       ]  6 of 100 completed

Success:    37/   37 | To go: 00:00:24 (  364)

[*********************100%***********************]  100 of 100 completed

44 Failed downloads:
['USARW', 'VEEAW', 'UYSCR', 'UKOMW', 'VACHW', 'UHGWW', 'USGOW', 'VAPEW', 'VCICW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['TZUP', 'UROY', 'UDMY', 'VERA', 'UPXI', 'VCIG', 'UYSCU', 'UNCY', 'USEA', 'USGO', 'VCIC', 'UCL', 'VALN', 'USAR', 'ULY', 'VBNK', 'VACH', 'VACHU', 'UPST', 'UYSC', 'USCB', 'TWNP', 'VCICU', 'UCAR', 'UPB', 'UFG', 'UHG', 'UBXG', 'VEEE', 'ULCC', 'VEEA', 'TYRA', 'UPC', 'UMBFO', 'TYGO']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
[**                     4%                       ]  4 of 100 completed

Success:    38/   38 | To go: 00:00:18 (  264)

[*********************100%***********************]  100 of 100 completed

39 Failed downloads:
['VRM', 'VMEO', 'VFS', 'WBTN', 'VSTA', 'VMAR', 'VOR', 'VVOS', 'VERX', 'VFSWW', 'WCT', 'WALD', 'VSME', 'VLYPN', 'VRAX', 'VOXR', 'VIGL', 'VRAR', 'WAI', 'WAY', 'WENNU', 'VSSYW', 'VGAS', 'WAFDP', 'VSEE', 'VNMEU', 'WALDW', 'WBUY', 'WENN', 'WEST', 'VITL', 'VWAV', 'VTYX', 'WAVE', 'VINP']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['VWAVW', 'WENNW', 'VGASW', 'VSEEW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[*                      2%                       ]  2 of 100 completed

Success:    39/   39 | To go: 00:00:11 (  164)

[*********************100%***********************]  100 of 100 completed

46 Failed downloads:
['WMG', 'XRTX', 'XCH', 'WFRD', 'WW', 'WETO', 'WLDS', 'WTGUU', 'XBP', 'WSBK', 'XAGE', 'XMTR', 'WIMI', 'XOS', 'WTFCN', 'WLAC', 'WSBCP', 'XHLD', 'WNW', 'WFF', 'WGRX', 'XLO', 'XOMAP', 'WRD', 'WYHG', 'WTF', 'WLGS', 'WLACU', 'WGS', 'WOK', 'WHFCL', 'XOMAO', 'XPON', 'WHLRL', 'WOOF', 'WTG', 'WTO', 'WETH', 'WXM']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')
['XBPEW', 'WLACW', 'WTGUR', 'XOSWW', 'WGSWW', 'XAGEW', 'WLDSW']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
[****                   8%                       ]  5 of 64 completed

Success:    40/   40 | To go: 00:00:04 (   64)

[*********************100%***********************]  62 of 64 completed

36 Failed downloads:
['ZOOZW', 'YORKW', 'ZEOWW', 'YHNAR']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31)')
['ZJK', 'ZCMD', 'YOSH', 'YOUL', 'YYGH', 'ZENA', 'ZDAI', 'YB', 'YMAT', 'ZIMV', 'ZJYL', 'ZURA', 'YGMZ', 'ZNTL', 'YXT', 'YORKU', 'YHNAU', 'ZSPC', 'ZBAO', 'YHNA', 'ZOOZ', 'YQ', 'YHC', 'YAAS', 'YYAI', 'ZENV', 'ZYBT', 'YIBO', 'ZEO', 'YORK', 'ZBIO', 'YSXT']: YFPricesMissingError('possibly delisted; no price data found  (1d 1990-01-01 -> 2019-12-31) (Yahoo error = "Data doesn\'t exist for startDate = 631170000, endDate = 1577768400")')

Success:    41/   41 | To go: -1:59:58 (  -36)

In [74]:
prices_adj = (
    pd.concat(prices_adj)
    .dropna(how="all", axis=1)
    .rename(columns=str.lower)
    .swaplevel()
)

In [75]:
prices_adj.index.names = ["ticker", "date"]

In [76]:
len(prices_adj.index.unique("ticker"))

2077

### Remove outliers

In [77]:
df = prices_adj.close.unstack("ticker")
pmax = df.pct_change().max()
pmin = df.pct_change().min()
to_drop = pmax[pmax > 1].index.union(pmin[pmin < -1].index)
len(to_drop)

375

In [78]:
prices_adj = prices_adj.drop(to_drop, level="ticker")

In [79]:
len(prices_adj.index.unique("ticker"))

1702

In [80]:
prices_adj

Price                  close       high        low       open       volume
ticker date
AAME   1990-01-02   2.206222   2.206222   1.985599   2.206222       8200.0
AAPL   1990-01-02   0.261499   0.263253   0.245704   0.247458  183198400.0
ACNT   1990-01-02   2.722866   2.722866   2.689660   2.689660       6750.0
ADBE   1990-01-02   1.188340   1.203010   1.144327   1.188340    7166400.0
ADI    1990-01-02   0.990637   1.016368   0.964906   1.016368     895800.0
...                      ...        ...        ...        ...          ...
ZTEK   2019-12-30   0.270000   0.280000   0.270000   0.280000      11500.0
ZUMZ   2019-12-30  33.959999  34.189999  32.330002  32.790001     472200.0
ZVRA   2019-12-30   6.720000   8.000000   6.688000   7.360000     194806.0
ZYME   2019-12-30  44.849998  45.590000  43.549999  44.560001     259900.0
ZYXI   2019-12-30   7.157002   7.300861   6.968187   7.237923     162910.0

[6078122 rows x 5 columns]

In [81]:
prices_adj.sort_index().loc[idx[:, '1990': '2019'], :]

Price                  close       high        low       open     volume
ticker date
AAL    2005-09-27  18.194912  20.174670  18.006365  19.844710   961200.0
       2005-09-28  19.326202  19.354485  18.100639  18.194912  5747900.0
       2005-09-29  19.052803  19.401618  18.949103  19.231924  1078200.0
       2005-09-30  19.806997  19.844706  19.024522  19.099941  3123300.0
       2005-10-03  20.268942  20.504627  19.703297  19.703297  1057900.0
...                      ...        ...        ...        ...        ...
ZYXI   2019-12-23   7.174984   7.327835   6.788362   6.860292   374990.0
       2019-12-24   7.327835   7.354809   6.977177   7.085072   147510.0
       2019-12-26   7.228932   7.426738   7.112046   7.291870   139700.0
       2019-12-27   7.237923   7.543624   7.157002   7.210949   260810.0
       2019-12-30   7.157002   7.300861   6.968187   7.237923   162910.0

[6078122 rows x 5 columns]

In [82]:
prices_adj.sort_index().loc[idx[:, '1990': '2019'], :].to_hdf(results_path / 'data.h5', 
                                                              'stocks/prices/adjusted')

In [54]:
data_final = data.sort_index().loc[idx[:, '2009':'2018'], :]

In [56]:
data_final.describe()

               open          high           low         close        volume
count  3.124659e+06  3.124659e+06  3.124659e+06  3.124659e+06  3.124659e+06
mean   1.255574e+09  1.352508e+09  1.131540e+09  1.271283e+09  2.193442e+06
std    1.207759e+11  1.326576e+11  9.464343e+10  1.206310e+11  2.541785e+07
min    4.200000e-03  4.600000e-03  1.400000e-03  1.500000e-03  0.000000e+00
25%    7.990000e+00  8.135000e+00  7.830000e+00  7.990000e+00  1.554700e+04
50%    1.690900e+01  1.720000e+01  1.660730e+01  1.691000e+01  1.082695e+05
75%    3.788640e+01  3.847890e+01  3.726665e+01  3.788590e+01  5.528005e+05
max    6.135446e+13  6.135446e+13  4.252298e+13  6.074696e+13  3.807199e+09

In [57]:
data_final.isnull().sum()

open      0
high      0
low       0
close     0
volume    0
dtype: int64

In [58]:
data_final.to_hdf(
    results_path / "data.h5", "stocks/prices/adjusted"
)